#!/usr/bin/env bash

# look at /var/log/ganeti/os/ for trace
[[ "${DEBUG_LEVEL:-}" -eq 1 ]] && set -x

set -euo pipefail
SELF_BASE="${0%/*}"

# common functions
. ${SELF_BASE}/common/common.sh
# global functions (the implementation of this os interface)
. ${SELF_BASE}/common/default.sh
# possible per variant function override 
if [ -r "${SELF_BASE}/${OS_VARIANT}/${OS_VARIANT}.sh" ]; then
  . ${SELF_BASE}/variants/${OS_VARIANT}.sh
fi

# defaults ENV for all variants
if [ -r "${SELF_BASE}/variants/default.env" ]; then
  . ${SELF_BASE}/variants/default.env
fi
# per site settings
if [ -r "${SELF_BASE}/variants/site.env" ]; then
  . ${SELF_BASE}/variants/site.env
fi
# per variant ENV vars = the config of the variant
. ${SELF_BASE}/variants/${OS_VARIANT}.env

flag_source_type
parse_source_uri

guestfish_start

instance_check
instance_prepare_before_copy
instance_copy
instance_prepare_after_copy

instance_configure
#if [ -f "${SELF_BASE}/variants/${OSP_ROLE}.sh" ]; then
#  . ${SELF_BASE}/variants/${OSP_ROLE}.sh
#  instance_apply_role
#fi
